/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
**********************************************************************
*                                                                    *
*        (c) 1996 - 2014  SEGGER Microcontroller GmbH & Co. KG       *
*                                                                    *
*        Internet: www.segger.com    Support:  support@segger.com    *
*                                                                    *
**********************************************************************

** emWin V5.26 - Graphical user interface for embedded applications **
emWin is protected by international copyright laws.   Knowledge of the
source code may not be used to write a similar product.  This file may
only be used in accordance with a license and should not be re-
distributed in any way. We appreciate your understanding and fairness.
----------------------------------------------------------------------
File        : MEMDEV_AutoDev.c
Purpose     : Example demonstrating the use of GUI_AUTODEV-objects
Requirements: WindowManager - ( )
              MemoryDevices - (x)
              AntiAliasing  - (x)
              VNC-Server    - ( )
              PNG-Library   - ( )
              TrueTypeFonts - ( )
----------------------------------------------------------------------
*/
#include "example.h"


/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#define ID_TIMER_SPEC       0  //定义第一个定时器
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END
extern GUI_CONST_STORAGE GUI_BITMAP bmlannge_yellow;  //橙色logo
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
static void DisWave(void)
{
	static unsigned int s_Spec_TopVal[32] = { 0 };  /*频谱顶值表*/
	static unsigned int s_Spec_CopVal[32] = { 0 };  /*频谱当前值表*/
	static unsigned int s_Spec_Time[32] = { 0 };  /*顶值停留时间表*/
	const  unsigned int usMaxVal = 128;               /* 高度固定为128个像素 */
	char i;
	int x=0;
	GUI_SetAlpha(0x80);
	/* 显示32条频谱 */
	for (i = 0; i < 31; i++)
	{
		GUI_DrawGradientV(x, (i * 5), x + 10, 230, GUI_YELLOW, GUI_GREEN);
		/* 显示顶值 */
		GUI_SetColor(GUI_RED);
		GUI_DrawHLine((i * 5), x, x + 10);
		x += 13;
	}
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	const   GUI_RECT  Rect = { 0, 0, 400, 240 }; /* 左上角x，y，右下角x，y*/
	static  WM_HTIMER hTimerSpec;  //定时器句柄
	int     NCode;
	int     Id;
	static int	backcolor = 0;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_INIT_DIALOG:
		hTimerSpec = WM_CreateTimer(pMsg->hWin, ID_TIMER_SPEC, 20, 0);
		break;

	case WM_TIMER:
		Id = WM_GetTimerId(pMsg->Data.v);
		switch (Id)
		{
		case ID_TIMER_SPEC:
			WM_InvalidateRect(pMsg->hWin, &Rect); //无效化部分界面
			WM_RestartTimer(pMsg->Data.v, 20);  //重新启动定时器
			break;
		}
		break;

	//绘制图画
	case WM_PAINT:
		
		//if (backcolor == 3)
		//{
		//	backcolor = -1;
		//}
		//else if (backcolor == 0)
		//{
		//	GUI_SetBkColor(GUI_RED);
		//	GUI_Clear();
		//}
		//else if (backcolor == 1)
		//{
		//	GUI_SetBkColor(GUI_GREEN);
		//	GUI_Clear();
		//}
		//else 
		//{
		//	GUI_SetBkColor(GUI_BLUE);
		//	GUI_Clear();
		//}
		//backcolor++;
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();
		GUI_DrawBitmap(&bmlannge_yellow, 100, 100);
		DisWave();  //显示频谱
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//频谱
WM_HWIN example(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
















