/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "Interface.h"
#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x05)
#define ID_BUTTON_4 (GUI_ID_USER + 0x06)
#define ID_BUTTON_5 (GUI_ID_USER + 0x07)
#define ID_TEXT_1 (GUI_ID_USER + 0x08)


#define Font_Text  GUI_FONT_24_1   //字体
extern GUI_CONST_STORAGE GUI_BITMAP bmlannge_yellow;  //橙色logo
extern GUI_CONST_STORAGE GUI_BITMAP bmlannge_white;   //白色logo
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Mainface", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 17, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 150, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 280, 65, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 17, 155, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 150, 155, 103, 71, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 280, 155, 103, 71, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 317, 16, 63, 20, 0, 0x64, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*
*********************************************************************************************************
*	函 数 名: _cbDialog
*	功能说明: 对话框回调函数
*	形    参: pMsg  回调参数
*	返 回 值: 无
*********************************************************************************************************
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem, hItem1;
	int     NCode;
	int     Id;


	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Text'
		//
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//		TEXT_SetText(hItem, "Lannge");
//		TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
//		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0xffffffff));

		//
		// 初始按钮控件 INPUT
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, "INPUT");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 COAX_IN
		//
		hItem1 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetText(hItem1, "COAX_IN");
		BUTTON_SetFont(hItem1, Font_Text);

		//
		// 初始按钮控件 Gen_Out
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, Font_Text);
		BUTTON_SetText(hItem, "Gen_Out");

		//
		// 初始按钮控件 OUTPUT
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetText(hItem, "OUTPUT");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 SYSTEM
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetText(hItem, "SYSTEM");
		BUTTON_SetFont(hItem, Font_Text);

		//
		// 初始按钮控件 MODE
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, Font_Text);
		BUTTON_SetText(hItem, "MODE");

		//
		// 初始Text控件  时钟
		//
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
//		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//		TEXT_SetText(hItem, "00:00");
//		TEXT_SetFont(hItem, GUI_FONT_24_1);
//		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0xffffffff));
		break;

	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
		{

		}
		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_BUTTON_0:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				
				/* 关闭当前对话框， 创建对话框2 */
//				GUI_EndDialog(pMsg->hWin, 0); 
//				CreateINPUT_CHANNEL();	//新的界面
				GUI_EndDialog(pMsg->hWin,0); //关闭当前窗口
				CreateINPUT_CHANNEL();  //显示输入通道界面
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				

				break;
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				
				break;
			case WM_NOTIFICATION_RELEASED:
				
				break;

			}
			break;
		case ID_BUTTON_2:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
		case ID_BUTTON_3:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
		case ID_BUTTON_4:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
		case ID_BUTTON_5:
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:

				break;

			}
			break;
			
		}
		break;
	
	case WM_PAINT:

		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();  //全屏黑色
		GUI_DrawGradientRoundedV(0, 0, 399, 50, 0, 0xC0CEDC, GUI_BLACK); //渐变
		//
//		GUI_DrawGradientRoundedV(0, 0, 399, 239, 0, 0xC0CEDC, GUI_BLACK);
		GUI_SetPenSize(3);
		GUI_SetColor(GUI_RED);
		GUI_DrawLine(0, 50, 400, 50); //画红线

		GUI_DrawBitmap(&bmlannge_yellow, 100, 0);

		//GUI_DrawGradientH(0, 46, 200 - 1, 240 - 4, 0xdda0dd, 0xe14169);
		//GUI_DrawGradientH(200, 46, 400 - 1, 240 - 4, 0xe14169, 0xdda0dd);
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMainface
*/
WM_HWIN CreateMainface(void);
WM_HWIN CreateMainface(void) {
	WM_HWIN hWin;
	/////////////
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	return hWin;
}


/*************************** End of file ****************************/
